// tableCardReducer
export const RESET_TABLE_CARDS_TO_DEFAULT = 'RESET_TABLE_CARDS_TO_DEFAULT';
export const DEAL_TABLE_CARDS = 'DEAL_TABLE_CARDS';

// tableCardStatusReducer
export const RESET_TABLE_CARD_STATUS_TO_DEFAULT = 'RESET_TABLE_CARD_STATUS_TO_DEFAULT';
export const SHOW_FLOP_CARDS = 'SHOW_FLOP_CARDS';
export const SHOW_TURN_CARDS = 'SHOW_TURN_CARDS';
export const SHOW_RIVER_CARD = 'SHOW_RIVER_CARD';

// playersReducer
export const RESET_PLAYERS_TO_DEFAULT = 'RESET_PLAYERS_TO_DEFAULT';
export const CREATE_PLAYERS = 'CREATE_PLAYERS';
export const DEAL_CARDS_TO_PLAYER = 'DEAL_CARDS_TO_PLAYER';
export const UPDATE_PLAYER_CASH = 'UPDATE_PLAYER_CASH';
export const UPDATE_PLAYER_ACTION_STATS = 'UPDATE_PLAYER_ACTION_STATS';
export const ADD_DETERMINED_HANDS_TO_PLAYERS = 'ADD_DETERMINED_HANDS_TO_PLAYERS';
export const AWARD_POT_TO_PLAYER = 'AWARD_POT_TO_PLAYER';
export const RESET_PLAYER_CURRENT_BETS = 'RESET_PLAYER_CURRENT_BETS';

// potReducer
export const RESET_POT_TO_DEFAULT = 'RESET_POT_TO_DEFAULT';
export const ADD_TO_POT = 'ADD_TO_POT';
// export const CLOSE_BETTING_ROUND = 'CLOSE_BETTING_ROUND';

// TODO: To be used later
export const START_NEW_GAME = 'START_NEW_GAME';
export const CREATE_THE_DECK = 'CREATE_THE_DECK';
