module.exports = function(sequelize, DataTypes) {
	var HandResult = sequelize.define('HandResult', {
		// Giving the Author model a name of type STRING
		gameId: DataTypes.INTEGER,
		flop: DataTypes.STRING,
		turn: DataTypes.STRING,
		river: DataTypes.STRING,
		restOfDeck: DataTypes.STRING,
		p1Id: DataTypes.INTEGER,
		p1Cards: DataTypes.STRING,
		p1Hand: DataTypes.STRING,
		p1WinLoseFold: DataTypes.STRING,
		p1NumKnockouts: DataTypes.INTEGER,
		p1StateMatch: DataTypes.BOOLEAN,
		p1State: DataTypes.STRING,
		p2Id: DataTypes.INTEGER,
		p2Cards: DataTypes.STRING,
		p2Hand: DataTypes.STRING,
		p2WinLoseFold: DataTypes.STRING,
		p2NumKnockouts: DataTypes.INTEGER,
		p2StateMatch: DataTypes.BOOLEAN,
		p2State: DataTypes.STRING,
		p3Id: DataTypes.INTEGER,
		p3Cards: DataTypes.STRING,
		p3Hand: DataTypes.STRING,
		p3WinLoseFold: DataTypes.STRING,
		p3NumKnockouts: DataTypes.INTEGER,
		p3StateMatch: DataTypes.BOOLEAN,
		p3State: DataTypes.STRING,
		p4Id: DataTypes.INTEGER,
		p4Cards: DataTypes.STRING,
		p4Hand: DataTypes.STRING,
		p4WinLoseFold: DataTypes.STRING,
		p4NumKnockouts: DataTypes.INTEGER,
		p4StateMatch: DataTypes.BOOLEAN,
		p4State: DataTypes.STRING,
		p5Id: DataTypes.INTEGER,
		p5Cards: DataTypes.STRING,
		p5Hand: DataTypes.STRING,
		p5WinLoseFold: DataTypes.STRING,
		p5NumKnockouts: DataTypes.INTEGER,
		p5StateMatch: DataTypes.BOOLEAN,
		p5State: DataTypes.STRING,
	});

	return HandResult;
};
